export const kpClerkAppearance = {
  variables: {
    colorBackground: "#0a0a0a",
    colorInputBackground: "#121212",
    colorInputText: "#f5f5f5",
    colorText: "rgba(255,255,255,0.92)",
    colorTextSecondary: "rgba(255,255,255,0.55)",
    colorPrimary: "#c9a962",
    colorDanger: "#e85d5d",
    borderRadius: "0.375rem",
    fontFamily: "var(--font-dm-sans), system-ui, sans-serif",
    fontFamilyButtons: "var(--font-dm-sans), system-ui, sans-serif",
  },
  elements: {
    rootBox: "w-full",
    cardBox: "w-full max-w-full shadow-none",
    card: "bg-transparent shadow-none border-0 p-0 gap-4",
    headerTitle: "font-serif text-xl tracking-wide text-white",
    headerSubtitle: "text-white/50 text-sm",
    socialButtonsBlockButton:
      "border border-white/15 bg-white/5 text-white hover:bg-white/10",
    formFieldInput:
      "border-white/15 bg-white/5 text-white placeholder:text-white/35",
    otpCodeFieldInput:
      "min-h-11 min-w-10 border border-white/25 bg-white/[0.08] text-white caret-white opacity-100",
    otpCodeFieldInputContainer: "flex justify-center",
    otpCodeFieldInputs: "flex min-h-11 justify-center gap-2",
    main: "flex flex-col gap-4",
    formResendCodeLink: "text-[#c9a962] hover:text-[#dfc88a]",
    formButtonPrimary:
      "bg-white text-black font-semibold uppercase tracking-[0.14em] text-[11px] hover:bg-white/90",
    footerActionLink: "text-[#c9a962] hover:text-[#dfc88a]",
    formFieldLabel: "text-white/60 uppercase text-[10px] tracking-[0.18em]",    dividerLine: "bg-white/10",
    dividerText: "text-white/40 text-[10px] uppercase tracking-[0.2em]",
    alternativeMethodsBlockButton:
      "border border-white/15 bg-white/5 text-white hover:bg-white/10",
    formFieldAction: "text-[#c9a962] hover:text-[#dfc88a]",
    formHeaderTitle: "font-serif text-lg tracking-wide text-white/90",
    formHeaderSubtitle: "text-white/55 text-sm leading-relaxed",
    identityPreview: "rounded-lg border border-white/10 bg-white/[0.04] px-4 py-3",
    identityPreviewText: "font-sans text-sm text-white/85",
    identityPreviewEditButton: "text-kp-gold hover:text-[#dfc88a] text-xs",
    formFieldInfoText: "text-white/45 text-xs",
    formFieldSuccessText: "text-emerald-400/90 text-xs",
    formFieldErrorText: "text-[#e85d5d] text-xs",
    alertText: "text-white/70 text-sm",
    backLink: "text-white/50 hover:text-white/80 text-xs",
    footerActionText: "text-white/45 text-sm",
  },
  captcha: {
    theme: "dark",
    size: "flexible",
    language: "auto",
  },
} as const;
