"use client";

import type { ReactNode } from "react";
import Image from "next/image";
import Link from "next/link";
import { Reveal } from "@/components/kp/Reveal";
import { useLocale } from "@/components/providers/KpLocaleProvider";

type Copy = { fr: string; en: string };

const HERO_BACKDROP = "/hero/pic21.png";
const CTA_BACKDROP = "/garage2.jpg";
const COMMITMENTS_BACKDROP = "/nature.jpg";
const PILLARS_NAV_BACKDROP = "/nature1.jpg";

const btnPrimary =
  "group inline-flex items-center justify-center gap-2 rounded-full bg-white px-7 py-3.5 text-[12px] font-semibold uppercase tracking-[0.2em] text-black transition-all duration-300 hover:scale-[1.02] hover:bg-white/90 active:scale-[0.98] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-400/55";

const btnGhost =
  "group inline-flex items-center justify-center gap-2 rounded-full border border-white/15 bg-white/5 px-7 py-3.5 text-[12px] font-semibold uppercase tracking-[0.2em] text-white/85 backdrop-blur-sm transition-all duration-300 hover:border-emerald-400/45 hover:bg-white/8 hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-400/55";

const eyebrow =
  "inline-flex items-center gap-3 text-[11px] font-semibold uppercase tracking-[0.28em] text-emerald-400/95";

const sectionPad =
  "mx-auto max-w-[1280px] px-5 py-16 sm:px-8 sm:py-20 md:py-28 lg:px-12";

const sectionTitle =
  "font-serif text-[clamp(1.75rem,4.2vw,3rem)] font-normal leading-[1.1] tracking-tight text-white";

const AMBITION_INTRO: Copy = {
  fr: "Notre ambition est de démontrer qu’une marque automobile ivoirienne constitue un vecteur de développement durable, en conjuguant excellence technologique, responsabilité environnementale et progrès social au bénéfice de la jeunesse ivoirienne.",
  en: "Our ambition is to demonstrate that an Ivorian car brand is a driver of sustainable development, combining technological excellence, environmental responsibility, and social progress for the benefit of Ivorian youth.",
};

const commitments: Copy[] = [
  { fr: "Certifications environnementales", en: "Environmental certifications" },
  {
    fr: "Actions sociales et environnementales",
    en: "Social and environmental initiatives",
  },
  {
    fr: "Réduction de la consommation d’énergie",
    en: "Reduced energy consumption",
  },
  { fr: "Gestion responsable des déchets", en: "Responsible waste management" },
];

const marqueeValues: Copy[] = [
  { fr: "Éclairages LED dans l’usine KPANDJI", en: "LED lighting in the KPANDJI factory" },
  {
    fr: "Machines industrielles basse consommation",
    en: "Low-consumption industrial machinery",
  },
  {
    fr: "Arrêt automatique des équipements inutilisés",
    en: "Automatic shutdown of idle equipment",
  },
  {
    fr: "Véhicules électriques pour la logistique interne",
    en: "Electric vehicles for internal logistics",
  },
  {
    fr: "Optimisation des transports et livraisons",
    en: "Optimized transport and deliveries",
  },
  {
    fr: "Recyclage des métaux, batteries et pneus",
    en: "Recycling of metals, batteries, and tires",
  },
  { fr: "Fournisseurs certifiés écologiques", en: "Certified eco-friendly suppliers" },
  { fr: "Véhicules hybrides ou électriques", en: "Hybrid or electric vehicles" },
  {
    fr: "Sensibilisation écologique du personnel",
    en: "Environmental awareness for staff",
  },
];

const pillars: {
  tag: Copy;
  title: Copy;
  body: Copy;
  image: string;
  alt: Copy;
  icon: ReactNode;
}[] = [
  {
    tag: { fr: "Souveraineté", en: "Sovereignty" },
    title: {
      fr: "Assemblage local & empreinte carbone",
      en: "Local assembly & carbon footprint",
    },
    body: {
      fr: "Pour la souveraineté et la réduction de l’empreinte carbone, l’assemblage local de nos modèles (DJETRAN, DJETRAN PLUS, LATHAYE, BANCO) réduit significativement les émissions de gaz à effet de serre générées par le transport maritime international de véhicules finis, renforçant ainsi notre indépendance industrielle.",
      en: "For sovereignty and a reduced carbon footprint, the local assembly of our models (DJETRAN, DJETRAN PLUS, LATHAYE, BANCO) significantly cuts the greenhouse gas emissions generated by international shipping of finished vehicles, strengthening our industrial independence.",
    },
    image: "/garage5.jpeg",
    alt: {
      fr: "Chaîne d’assemblage KPANDJI en Côte d’Ivoire",
      en: "KPANDJI assembly line in Côte d’Ivoire",
    },
    icon: (
      <>
        <path d="M4 10h16M6 10V7a2 2 0 012-2h8a2 2 0 012 2v3" strokeLinecap="round" />
        <path d="M8 14h8M10 18h4" strokeLinecap="round" />
        <rect x="3" y="10" width="18" height="8" rx="1" />
      </>
    ),
  },
  {
    tag: { fr: "Éco-citoyenneté", en: "Eco-citizenship" },
    title: { fr: "Partenariat avec des ONG", en: "Partnership with NGOs" },
    body: {
      fr: "Pour l’initiative éco-citoyenne, nous poursuivons et renforçons notre partenariat stratégique avec plusieurs ONG et fondations pour des campagnes nationales de reboisement, contribuant activement à la restauration et à la préservation du couvert forestier ivoirien.",
      en: "As part of our eco-citizen initiative, we maintain and strengthen strategic partnerships with several NGOs and foundations for national reforestation campaigns, actively contributing to restoring and preserving Ivorian forest cover.",
    },
    image: "/hero/pic21.png",
    alt: {
      fr: "Engagement KPANDJI pour la préservation de l’environnement",
      en: "KPANDJI's commitment to protecting the environment",
    },
    icon: (
      <>
        <path d="M12 22c-4-3-7-6-7-10a7 7 0 0114 0c0 4-3 7-7 10z" strokeLinejoin="round" />
        <path d="M12 12v-2M9 14h6" strokeLinecap="round" />
      </>
    ),
  },
  {
    tag: { fr: "Éco-conception", en: "Eco-design" },
    title: {
      fr: "Matériaux durables & efficacité énergétique",
      en: "Sustainable materials & energy efficiency",
    },
    body: {
      fr: "Pour l’éco-conception, nous nous engageons dans l’intégration progressive de matériaux durables et l’optimisation de la consommation énergétique de nos modèles, particulièrement adaptés aux conditions de circulation du Grand Abidjan.",
      en: "For eco-design, we are committed to progressively integrating sustainable materials and optimizing the energy consumption of our models, especially suited to driving conditions in Greater Abidjan.",
    },
    image: "/Interior_TA_4x4_Diesel_1_18ed005af5.jpg",
    alt: {
      fr: "Habitacle KPANDJI : technologies adaptées aux usages locaux",
      en: "KPANDJI cabin: technology adapted to local uses",
    },
    icon: (
      <>
        <circle cx="12" cy="12" r="3" />
        <path
          d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"
          strokeLinecap="round"
        />
      </>
    ),
  },
];

function SectionIntro({
  label,
  title,
  titleId,
  description,
}: {
  label: string;
  title: string;
  titleId?: string;
  description: string;
}) {
  return (
    <div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between lg:gap-12">
      <div>
        <p className={eyebrow}>
          <span aria-hidden className="h-px w-8 bg-emerald-400/60" />
          {label}
        </p>
        <h2 id={titleId} className={`mt-4 sm:mt-5 ${sectionTitle}`}>
          {title}
        </h2>
      </div>
      <p className="max-w-md text-[14px] leading-relaxed text-white/55 md:text-[15px] lg:max-w-sm lg:pb-1 lg:text-right">
        {description}
      </p>
    </div>
  );
}

export default function EcologyPageContent() {
  const { tr } = useLocale();

  return (
    <div className="min-h-screen bg-kp-bg text-kp-accent">
      <main>
        {/* HERO */}
        <section
          aria-label="ECO KPANDJI — KPANDJI AUTOMOBILES"
          className="relative isolate flex min-h-svh items-end overflow-hidden pt-[100px] sm:pt-[110px] md:pt-[132px]"
        >
          <div className="absolute inset-0 -z-10">
            <Image
              src={HERO_BACKDROP}
              alt={tr(
                "Engagement environnemental KPANDJI AUTOMOBILES",
                "KPANDJI AUTOMOBILES environmental commitment"
              )}
              fill
              priority
              sizes="100vw"
              className="object-cover object-center kp-hero-zoom"
            />
          </div>
          <div
            aria-hidden
            className="pointer-events-none absolute inset-0 -z-10 bg-linear-to-b from-emerald-950/50 via-black/55 to-black/95"
          />
          <div
            aria-hidden
            className="pointer-events-none absolute inset-0 -z-10 bg-[radial-gradient(900px_520px_at_15%_20%,rgba(52,211,153,0.22),transparent_58%),radial-gradient(800px_600px_at_85%_40%,rgba(201,169,98,0.14),transparent_55%),radial-gradient(900px_700px_at_50%_50%,transparent_50%,rgba(0,0,0,0.82)_100%)]"
          />
          <div
            aria-hidden
            className="kp-grain pointer-events-none absolute inset-0 -z-10 opacity-[0.32] mix-blend-overlay"
          />

          <div
            aria-hidden
            className="pointer-events-none absolute right-8 top-1/2 hidden -translate-y-1/2 lg:block"
          >
            <div className="flex flex-col items-center gap-4">
              <span className="text-[10px] font-semibold uppercase tracking-[0.4em] text-emerald-300/70 [writing-mode:vertical-rl]">
                ECO KPANDJI
              </span>
              <span className="h-24 w-px bg-linear-to-b from-emerald-400/70 via-emerald-400/25 to-transparent" />
            </div>
          </div>

          <div className="relative z-10 mx-auto w-full max-w-[1280px] px-5 pb-8 sm:px-8 sm:pb-32 md:pb-36 lg:px-12">
            <Reveal from="bottom">
              <p className={eyebrow}>
                <span aria-hidden className="h-px w-10 bg-emerald-400/80 sm:w-16" />
                ECO KPANDJI
              </p>
            </Reveal>

            <Reveal from="bottom" delayMs={120}>
              <h1 className="mt-5 max-w-[16ch] font-serif text-[clamp(2rem,7.5vw,5rem)] font-medium leading-[1.04] tracking-[-0.025em] text-white sm:max-w-[22ch]">
                <span className="block">{tr("Un vecteur de", "A driver of")}</span>
                <span className="block bg-linear-to-r from-white via-emerald-100/90 to-emerald-400/85 bg-clip-text text-transparent">
                  {tr("développement durable", "sustainable development")}
                </span>
              </h1>
            </Reveal>

            <Reveal from="bottom" delayMs={200}>
              <p className="mt-6 max-w-2xl text-pretty text-[15px] leading-relaxed text-white/72 sm:text-[16px] md:text-[17px]">
                {tr(AMBITION_INTRO.fr, AMBITION_INTRO.en)}
              </p>
            </Reveal>

            <Reveal from="bottom" delayMs={280}>
              <div className="mt-8 flex flex-col gap-3 sm:mt-9 sm:flex-row sm:flex-wrap sm:items-center sm:gap-4">
                <Link href="#engagements" className={`${btnPrimary} w-full sm:w-auto`}>
                  <span>{tr("Nos engagements", "Our commitments")}</span>
                  <svg
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="1.8"
                    className="size-3.5 transition-transform duration-300 group-hover:translate-y-0.5"
                    aria-hidden
                  >
                    <path
                      d="M12 5v14M5 12l7 7 7-7"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    />
                  </svg>
                </Link>
                <Link href="#pratiques" className={`${btnGhost} w-full sm:w-auto`}>
                  {tr("Nos pratiques usine", "Our factory practices")}
                </Link>
              </div>
            </Reveal>
          </div>
        </section>

        {/* COMMITMENTS - mobile first below hero */}
        <section
          aria-label={tr("Engagements environnementaux", "Environmental commitments")}
          className="border-b border-white/8 bg-kp-surface md:hidden"
        >
          <div className="mx-auto max-w-[1280px] px-5 py-8">
            <p className={eyebrow}>
              <span aria-hidden className="h-px w-8 bg-emerald-400/60" />
              {tr("Nos priorités", "Our priorities")}
            </p>
            <ul className="mt-5 grid gap-3">
              {commitments.map((c, i) => (
                <li
                  key={c.fr}
                  className="flex items-start gap-3 rounded-xl border border-white/8 bg-kp-elevated/30 px-4 py-3.5"
                >
                  <span className="mt-0.5 font-serif text-sm font-medium text-emerald-400/90">
                    {String(i + 1).padStart(2, "0")}
                  </span>
                  <span className="text-[13px] leading-snug text-white/75">
                    {tr(c.fr, c.en)}
                  </span>
                </li>
              ))}
            </ul>
          </div>
        </section>

        {/* MARQUEE */}
        <section
          id="pratiques"
          aria-label={tr("Pratiques usine", "Factory practices")}
          className="relative overflow-hidden border-y border-white/8 bg-kp-surface py-6 sm:py-7"
        >
          <div className="pointer-events-none absolute inset-y-0 left-0 z-10 w-16 bg-linear-to-r from-kp-surface to-transparent sm:w-24" />
          <div className="pointer-events-none absolute inset-y-0 right-0 z-10 w-16 bg-linear-to-l from-kp-surface to-transparent sm:w-24" />
          <p className="sr-only">
            {tr("Pratiques écologiques en usine KPANDJI", "Eco-friendly practices at the KPANDJI factory")}
          </p>
          <div className="kp-marquee-track flex w-max items-center gap-8 whitespace-nowrap text-white/55 sm:gap-12">
            {[...Array(2)].map((_, dup) => (
              <div key={dup} className="flex items-center gap-8 sm:gap-12">
                {marqueeValues.map((v, i) => (
                  <span
                    key={`${dup}-${i}`}
                    className="flex max-w-[min(90vw,420px)] items-center gap-6 font-serif text-base font-normal tracking-tight sm:max-w-none sm:gap-8 sm:text-xl md:text-2xl"
                  >
                    <span>{tr(v.fr, v.en)}</span>
                    <span className="size-1.5 shrink-0 rounded-full bg-emerald-400/80" />
                  </span>
                ))}
              </div>
            ))}
          </div>
        </section>

        {/* COMMITMENTS desktop */}
        <section
          aria-label={tr("Engagements environnementaux", "Environmental commitments")}
          className="relative isolate hidden overflow-hidden border-b border-white/8 md:block"
        >
          <div className="absolute inset-0 -z-10">
            <Image
              src={COMMITMENTS_BACKDROP}
              alt=""
              fill
              sizes="100vw"
              className="object-cover object-center"
            />
          </div>
          <div
            aria-hidden
            className="pointer-events-none absolute inset-0 -z-10 bg-linear-to-b from-kp-surface/94 via-kp-surface/58 to-kp-surface/52"
          />

          <div className={`relative z-10 ${sectionPad}`}>
            <Reveal from="bottom">
              <p className={eyebrow}>
                <span aria-hidden className="h-px w-8 bg-emerald-400/60" />
                {tr("Nos priorités", "Our priorities")}
              </p>
              <h2 className={`mt-5 ${sectionTitle}`}>
                {tr(
                  "Une industrie responsable, à chaque étape.",
                  "A responsible industry, every step of the way."
                )}
              </h2>
            </Reveal>
            <ul className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4 lg:gap-5">
              {commitments.map((c, i) => (
                <Reveal key={c.fr} from="bottom" delayMs={i * 50}>
                  <li className="group flex h-full flex-col rounded-2xl border border-white/8 bg-kp-elevated/25 p-6 transition-all duration-500 hover:-translate-y-0.5 hover:border-emerald-400/25 hover:bg-kp-elevated/40">
                    <span className="font-serif text-3xl font-medium leading-none text-emerald-400/25 transition-colors duration-500 group-hover:text-emerald-400/40">
                      {String(i + 1).padStart(2, "0")}
                    </span>
                    <p className="mt-4 text-[20px] leading-relaxed text-white/75 md:text-[20px]">
                      {tr(c.fr, c.en)}
                    </p>
                  </li>
                </Reveal>
              ))}
            </ul>
          </div>
        </section>

        {/* PILLARS NAV */}
        <section
          aria-label={tr("Aperçu des leviers", "Overview of our levers")}
          className="relative isolate overflow-hidden bg-kp-bg"
        >
          <div className="absolute inset-0 -z-10">
            <Image
              src={PILLARS_NAV_BACKDROP}
              alt=""
              fill
              sizes="100vw"
              className="object-cover object-center opacity-30"
            />
          </div>
          <div
            aria-hidden
            className="pointer-events-none absolute inset-0 -z-10 bg-linear-to-b from-kp-bg/92 via-kp-bg/90 to-kp-bg/92"
          />
          <div
            aria-hidden
            className="pointer-events-none absolute inset-0 -z-10 bg-[radial-gradient(900px_520px_at_50%_40%,rgba(52,211,153,0.1),transparent_58%)]"
          />
          <div className="relative z-10 mx-auto max-w-[1280px] px-5 py-10 sm:px-8 sm:py-12 lg:px-12">
            <div className="grid gap-3 sm:grid-cols-3 sm:gap-4">
              {pillars.map((p, i) => (
                <Reveal key={p.tag.fr} from="bottom" delayMs={i * 50}>
                  <a
                    href="#engagements"
                    className="group flex h-full flex-col rounded-2xl border border-white/8 bg-kp-elevated/20 p-5 transition-all duration-500 hover:-translate-y-0.5 hover:border-emerald-400/25 hover:bg-kp-elevated/35 sm:p-6"
                  >
                    <span className="text-[15px] font-semibold uppercase tracking-[0.14em] text-emerald-400/90">
                      {tr(p.tag.fr, p.tag.en)}
                    </span>
                    <span className="mt-3 font-serif text-lg leading-snug tracking-tight text-white sm:text-2xl">
                      {tr(p.title.fr, p.title.en)}
                    </span>
                    <span className="mt-4 inline-flex items-center gap-1.5 text-[15px] font-semibold uppercase tracking-[0.2em] text-white/45 transition-colors group-hover:text-emerald-400/85">
                      {tr("En savoir plus", "Learn more")}
                      <svg
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        strokeWidth="1.8"
                        className="size-3 transition-transform duration-300 group-hover:translate-x-0.5"
                        aria-hidden
                      >
                        <path
                          d="M5 12h14M13 6l6 6-6 6"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        />
                      </svg>
                    </span>
                  </a>
                </Reveal>
              ))}
            </div>
          </div>
        </section>

        {/* GALLERY */}
        <section
          aria-labelledby="terrain-heading"
          className="relative isolate overflow-hidden bg-kp-bg"
        >
          <div
            aria-hidden
            className="pointer-events-none absolute inset-0 -z-10 bg-[radial-gradient(800px_500px_at_50%_0%,rgba(52,211,153,0.08),transparent_60%)]"
          />
          <div className={sectionPad}>
            <Reveal from="bottom">
              <SectionIntro
                label={tr("Industrie locale", "Local industry")}
                title={tr("L'assemblage en images.", "Assembly, in pictures.")}
                titleId="terrain-heading"
                description={tr(
                  "Nos sites de production et d'entretien incarnent la souveraineté industrielle et l'exigence environnementale de KPANDJI.",
                  "Our production and maintenance sites embody KPANDJI's industrial sovereignty and environmental standards."
                )}
              />
            </Reveal>

            <Reveal from="bottom" delayMs={120}>
              <div className="mt-10 grid grid-cols-1 gap-4 sm:mt-12 sm:grid-cols-2 md:mt-16 lg:grid-cols-3 lg:grid-rows-2 lg:gap-5">
                <figure className="group relative overflow-hidden rounded-2xl border border-white/10 bg-kp-elevated/40 sm:col-span-2 lg:col-span-2 lg:row-span-2">
                  <div className="relative aspect-16/10 w-full sm:aspect-2/1 lg:aspect-auto lg:min-h-[min(52vh,520px)]">
                    <Image
                      src="/garage5.jpeg"
                      alt={tr(
                        "Infrastructure KPANDJI — montage et contrôle qualité",
                        "KPANDJI infrastructure — assembly and quality control"
                      )}
                      fill
                      sizes="(max-width: 768px) 100vw, 66vw"
                      className="object-cover transition-transform duration-1000 group-hover:scale-[1.04]"
                    />
                    <div
                      aria-hidden
                      className="pointer-events-none absolute inset-0 bg-linear-to-t from-black/85 via-black/15 to-transparent"
                    />
                    <span className="absolute left-4 top-4 inline-flex items-center gap-2 rounded-full border border-white/15 bg-black/45 px-3 py-1 text-[10px] font-semibold uppercase tracking-[0.24em] text-white/85 backdrop-blur-md sm:left-6 sm:top-6">
                      <span className="size-1 rounded-full bg-emerald-400/95" />
                      {tr("01 — Assemblage", "01 — Assembly")}
                    </span>
                    <figcaption className="absolute inset-x-0 bottom-0 p-5 sm:p-6 md:p-8">
                      <p className="text-[11px] font-semibold uppercase tracking-[0.22em] text-emerald-400/95">
                        {tr("Souveraineté", "Sovereignty")}
                      </p>
                      <p className="mt-2 font-serif text-xl font-medium text-white sm:text-2xl md:text-3xl">
                        {tr("Produire localement", "Producing locally")}
                      </p>
                    </figcaption>
                  </div>
                </figure>

                <figure className="group relative overflow-hidden rounded-2xl border border-white/10 bg-kp-elevated/40">
                  <div className="relative aspect-16/10 w-full sm:aspect-4/3 lg:aspect-auto lg:min-h-[240px]">
                    <Image
                      src="/garage2.jpg"
                      alt={tr("Atelier KPANDJI — espace structuré", "KPANDJI workshop — organized space")}
                      fill
                      sizes="(max-width: 768px) 100vw, 33vw"
                      className="object-cover transition-transform duration-1000 group-hover:scale-[1.05]"
                    />
                    <div
                      aria-hidden
                      className="pointer-events-none absolute inset-0 bg-linear-to-t from-black/80 via-black/10 to-transparent"
                    />
                    <span className="absolute left-4 top-4 inline-flex items-center gap-2 rounded-full border border-white/15 bg-black/45 px-3 py-1 text-[10px] font-semibold uppercase tracking-[0.24em] text-white/85 backdrop-blur-md sm:left-5 sm:top-5">
                      <span className="size-1 rounded-full bg-emerald-400/95" />
                      {tr("02 — Atelier", "02 — Workshop")}
                    </span>
                    <figcaption className="absolute inset-x-0 bottom-0 p-4 sm:p-5">
                      <p className="font-serif text-lg font-medium text-white">
                        {tr("Chaîne maîtrisée", "A controlled production line")}
                      </p>
                    </figcaption>
                  </div>
                </figure>

                <figure className="group relative overflow-hidden rounded-2xl border border-white/10 bg-kp-elevated/40">
                  <div className="relative aspect-16/10 w-full sm:aspect-4/3 lg:aspect-auto lg:min-h-[240px]">
                    <Image
                      src="/garage3.jpg"
                      alt={tr("Maintenance et traitement maîtrisés", "Controlled maintenance and processing")}
                      fill
                      sizes="(max-width: 768px) 100vw, 33vw"
                      className="object-cover transition-transform duration-1000 group-hover:scale-[1.05]"
                    />
                    <div
                      aria-hidden
                      className="pointer-events-none absolute inset-0 bg-linear-to-t from-black/80 via-black/10 to-transparent"
                    />
                    <span className="absolute left-4 top-4 inline-flex items-center gap-2 rounded-full border border-white/15 bg-black/45 px-3 py-1 text-[10px] font-semibold uppercase tracking-[0.24em] text-white/85 backdrop-blur-md sm:left-5 sm:top-5">
                      <span className="size-1 rounded-full bg-emerald-400/95" />
                      {tr("03 — SAV", "03 — After-sales")}
                    </span>
                    <figcaption className="absolute inset-x-0 bottom-0 p-4 sm:p-5">
                      <p className="font-serif text-lg font-medium text-white">
                        {tr("Qualité & SAV", "Quality & after-sales")}
                      </p>
                    </figcaption>
                  </div>
                </figure>
              </div>
            </Reveal>
          </div>
        </section>

        {/* CTA */}
        <section
          aria-labelledby="ecologie-cta"
          className="relative isolate overflow-hidden bg-kp-bg"
        >
          <div className="absolute inset-0 -z-10">
            <Image
              src={CTA_BACKDROP}
              alt=""
              fill
              sizes="100vw"
              className="object-cover object-center opacity-20"
            />
          </div>
          <div
            aria-hidden
            className="pointer-events-none absolute inset-0 -z-10 bg-linear-to-b from-kp-bg via-kp-bg/88 to-kp-bg"
          />
          <div
            aria-hidden
            className="pointer-events-none absolute inset-0 -z-10 bg-[radial-gradient(900px_520px_at_50%_50%,rgba(52,211,153,0.14),transparent_60%)]"
          />
          <div
            aria-hidden
            className="pointer-events-none absolute inset-x-0 top-0 h-px bg-linear-to-r from-transparent via-emerald-400/45 to-transparent"
          />

          <div
            className={`${sectionPad} mx-auto max-w-[1100px] text-center py-20! sm:py-24! md:py-32!`}
          >
            <Reveal from="bottom">
              <div className="mx-auto flex w-full max-w-sm items-center gap-3">
                <span
                  aria-hidden
                  className="h-px flex-1 bg-linear-to-r from-transparent via-emerald-400/45 to-emerald-400/20"
                />
                <span
                  aria-hidden
                  className="size-1.5 shrink-0 rounded-full bg-emerald-400/95 shadow-[0_0_14px_rgba(52,211,153,0.4)]"
                />
                <span
                  aria-hidden
                  className="h-px flex-1 bg-linear-to-l from-transparent via-emerald-400/45 to-emerald-400/20"
                />
              </div>
            </Reveal>

            <Reveal from="bottom" delayMs={80}>
              <p className={`${eyebrow} mt-7 justify-center`}>
                {tr("Partenariats & questions", "Partnerships & questions")}
              </p>
            </Reveal>

            <Reveal from="bottom" delayMs={140}>
              <h2
                id="ecologie-cta"
                className="mt-5 font-serif text-[clamp(2rem,4.8vw,3.5rem)] font-normal leading-[1.06] tracking-tight text-white"
              >
                {tr("Aller plus loin", "Going further")}
                <br className="hidden sm:block" />
                <span className="bg-linear-to-r from-emerald-300 via-emerald-400/90 to-white/85 bg-clip-text text-transparent">
                  {" "}
                  {tr("ensemble", "together")}
                </span>
              </h2>
            </Reveal>

            <Reveal from="bottom" delayMs={220}>
              <p className="mx-auto mt-6 max-w-2xl text-pretty text-[15px] leading-relaxed text-white/70 md:text-[16px]">
                {tr(
                  "Vous partagez notre vision d'une industrie automobile ivoirienne responsable ? Contactez-nous pour échanger sur nos engagements ECO KPANDJI.",
                  "Do you share our vision of a responsible Ivorian automotive industry? Contact us to discuss our ECO KPANDJI commitments."
                )}
              </p>
            </Reveal>

            <Reveal from="bottom" delayMs={300}>
              <div className="mt-10 flex flex-col items-stretch justify-center gap-3 sm:flex-row sm:flex-wrap sm:items-center sm:gap-4">
                <Link href="/contact" className={`${btnPrimary} w-full sm:w-auto`}>
                  <span>{tr("Nous contacter", "Contact us")}</span>
                  <svg
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="1.8"
                    className="size-3.5 transition-transform duration-300 group-hover:translate-x-0.5"
                    aria-hidden
                  >
                    <path
                      d="M5 12h14M13 6l6 6-6 6"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    />
                  </svg>
                </Link>
                <Link
                  href="/service-apres-vente"
                  className={`${btnGhost} w-full sm:w-auto`}
                >
                  {tr("Service après-vente", "After-sales service")}
                </Link>
                <Link
                  href="/kpandji-automobiles"
                  className="inline-flex w-full items-center justify-center rounded-full border border-white/10 px-6 py-3.5 text-[12px] font-semibold uppercase tracking-[0.2em] text-white/60 transition-all duration-300 hover:border-white/20 hover:text-white/85 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-400/55 sm:w-auto"
                >
                  {tr("L'entreprise", "The company")}
                </Link>
              </div>
            </Reveal>

            <Reveal from="bottom" delayMs={380}>
              <div className="mt-14 flex flex-col items-center gap-3 text-[10px] uppercase tracking-[0.32em] text-white/35 sm:flex-row sm:justify-center sm:gap-6">
                <span>{tr("Assemblage local", "Local assembly")}</span>
                <span
                  aria-hidden
                  className="hidden size-1 rounded-full bg-emerald-400/40 sm:block"
                />
                <span>{tr("Partenariats ONG", "NGO partnerships")}</span>
                <span
                  aria-hidden
                  className="hidden size-1 rounded-full bg-emerald-400/40 sm:block"
                />
                <span>{tr("Éco-conception", "Eco-design")}</span>
              </div>
            </Reveal>
          </div>
        </section>
      </main>
    </div>
  );
}
